# gui\dialogs\control_data_folder\pages\base.py

from __future__ import annotations


class ControlDataPage:
    title: str

    def get_length_labels(self) -> list: ...
    def get_force_labels(self) -> list: ...

    def set_state_from_model(self, model) -> None: ...
    def apply_to_model(self, model) -> None: ...
    def validate(self) -> tuple[bool, str]: ...

    # Called when units change; prev_len may equal new_len on first call.
    def on_units_changed(self, units, prev_len: str, new_len: str, prev_force: str, new_force: str) -> None: ...
